/* AUTO-GENERATED FILE.  DO NOT MODIFY.
 *
 * This class was automatically generated by the
 * aapt tool from the resource data it found.  It
 * should not be modified by hand.
 */

package net.karazy.cloobster.frizz;

public final class R {
    public static final class array {
        public static final int country_codes=0x7f0a0000;
    }
    public static final class attr {
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int confirm_logout=0x7f01000c;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int done_button_background=0x7f010006;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int done_button_text=0x7f010004;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int extra_fields=0x7f010001;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int fetch_user_info=0x7f01000d;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int is_cropped=0x7f010011;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int login_text=0x7f01000e;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int logout_text=0x7f01000f;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int multi_select=0x7f010007;
        /** <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
         */
        public static final int preset_size=0x7f010010;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int radius_in_meters=0x7f010008;
        /** <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int results_limit=0x7f010009;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int search_text=0x7f01000a;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_pictures=0x7f010000;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_search_box=0x7f01000b;
        /** <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int show_title_bar=0x7f010002;
        /** <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
         */
        public static final int title_bar_background=0x7f010005;
        /** <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
         */
        public static final int title_text=0x7f010003;
    }
    public static final class color {
        public static final int com_facebook_blue=0x7f070002;
        public static final int com_facebook_loginview_text_color=0x7f070006;
        public static final int com_facebook_picker_search_bar_background=0x7f070000;
        public static final int com_facebook_picker_search_bar_text=0x7f070001;
        public static final int com_facebook_usersettingsfragment_connected_shadow_color=0x7f070004;
        public static final int com_facebook_usersettingsfragment_connected_text_color=0x7f070003;
        public static final int com_facebook_usersettingsfragment_not_connected_text_color=0x7f070005;
        public static final int contents_text=0x7f070007;
        public static final int encode_view=0x7f070008;
        public static final int possible_result_points=0x7f070009;
        /**  Android standard ICS color 
         */
        public static final int result_minor_text=0x7f07000a;
        public static final int result_points=0x7f07000b;
        /**  Android standard ICS color 
         */
        public static final int result_text=0x7f07000c;
        public static final int result_view=0x7f07000d;
        public static final int status_text=0x7f07000e;
        public static final int transparent=0x7f07000f;
        public static final int viewfinder_laser=0x7f070010;
        /**  Android standard ICS color 
         */
        public static final int viewfinder_mask=0x7f070011;
    }
    public static final class dimen {
        public static final int com_facebook_loginview_compound_drawable_padding=0x7f060008;
        public static final int com_facebook_loginview_padding_bottom=0x7f060007;
        public static final int com_facebook_loginview_padding_left=0x7f060004;
        public static final int com_facebook_loginview_padding_right=0x7f060005;
        public static final int com_facebook_loginview_padding_top=0x7f060006;
        public static final int com_facebook_loginview_text_size=0x7f060009;
        public static final int com_facebook_picker_divider_width=0x7f060001;
        public static final int com_facebook_picker_place_image_size=0x7f060000;
        public static final int com_facebook_profilepictureview_preset_size_large=0x7f06000c;
        public static final int com_facebook_profilepictureview_preset_size_normal=0x7f06000b;
        public static final int com_facebook_profilepictureview_preset_size_small=0x7f06000a;
        public static final int com_facebook_tooltip_horizontal_padding=0x7f06000d;
        public static final int com_facebook_usersettingsfragment_profile_picture_height=0x7f060003;
        public static final int com_facebook_usersettingsfragment_profile_picture_width=0x7f060002;
        public static final int half_padding=0x7f06000f;
        public static final int standard_padding=0x7f06000e;
    }
    public static final class drawable {
        public static final int com_facebook_button_blue=0x7f020000;
        public static final int com_facebook_button_blue_focused=0x7f020001;
        public static final int com_facebook_button_blue_normal=0x7f020002;
        public static final int com_facebook_button_blue_pressed=0x7f020003;
        public static final int com_facebook_button_check=0x7f020004;
        public static final int com_facebook_button_check_off=0x7f020005;
        public static final int com_facebook_button_check_on=0x7f020006;
        public static final int com_facebook_button_grey_focused=0x7f020007;
        public static final int com_facebook_button_grey_normal=0x7f020008;
        public static final int com_facebook_button_grey_pressed=0x7f020009;
        public static final int com_facebook_close=0x7f02000a;
        public static final int com_facebook_inverse_icon=0x7f02000b;
        public static final int com_facebook_list_divider=0x7f02000c;
        public static final int com_facebook_list_section_header_background=0x7f02000d;
        public static final int com_facebook_loginbutton_silver=0x7f02000e;
        public static final int com_facebook_logo=0x7f02000f;
        public static final int com_facebook_picker_default_separator_color=0x7f020031;
        public static final int com_facebook_picker_item_background=0x7f020010;
        public static final int com_facebook_picker_list_focused=0x7f020011;
        public static final int com_facebook_picker_list_longpressed=0x7f020012;
        public static final int com_facebook_picker_list_pressed=0x7f020013;
        public static final int com_facebook_picker_list_selector=0x7f020014;
        public static final int com_facebook_picker_list_selector_background_transition=0x7f020015;
        public static final int com_facebook_picker_list_selector_disabled=0x7f020016;
        public static final int com_facebook_picker_magnifier=0x7f020017;
        public static final int com_facebook_picker_top_button=0x7f020018;
        public static final int com_facebook_place_default_icon=0x7f020019;
        public static final int com_facebook_profile_default_icon=0x7f02001a;
        public static final int com_facebook_profile_picture_blank_portrait=0x7f02001b;
        public static final int com_facebook_profile_picture_blank_square=0x7f02001c;
        public static final int com_facebook_tooltip_black_background=0x7f02001d;
        public static final int com_facebook_tooltip_black_bottomnub=0x7f02001e;
        public static final int com_facebook_tooltip_black_topnub=0x7f02001f;
        public static final int com_facebook_tooltip_black_xout=0x7f020020;
        public static final int com_facebook_tooltip_blue_background=0x7f020021;
        public static final int com_facebook_tooltip_blue_bottomnub=0x7f020022;
        public static final int com_facebook_tooltip_blue_topnub=0x7f020023;
        public static final int com_facebook_tooltip_blue_xout=0x7f020024;
        public static final int com_facebook_top_background=0x7f020025;
        public static final int com_facebook_top_button=0x7f020026;
        public static final int com_facebook_usersettingsfragment_background_gradient=0x7f020027;
        public static final int ic_action_next_item=0x7f020028;
        public static final int ic_action_previous_item=0x7f020029;
        public static final int ic_action_remove=0x7f02002a;
        public static final int icon=0x7f02002b;
        public static final int launcher_icon=0x7f02002c;
        public static final int screen=0x7f02002d;
        public static final int share_via_barcode=0x7f02002e;
        public static final int shopper_icon=0x7f02002f;
        public static final int splash=0x7f020030;
    }
    public static final class id {
        public static final int back_button=0x7f0b0036;
        public static final int barcode_image_view=0x7f0b000f;
        public static final int bookmark_title=0x7f0b000a;
        public static final int bookmark_url=0x7f0b000b;
        public static final int com_facebook_body_frame=0x7f0b002c;
        public static final int com_facebook_button_xout=0x7f0b002e;
        public static final int com_facebook_login_activity_progress_bar=0x7f0b001c;
        public static final int com_facebook_picker_activity_circle=0x7f0b001b;
        public static final int com_facebook_picker_checkbox=0x7f0b001e;
        public static final int com_facebook_picker_checkbox_stub=0x7f0b0022;
        public static final int com_facebook_picker_divider=0x7f0b0026;
        public static final int com_facebook_picker_done_button=0x7f0b0025;
        public static final int com_facebook_picker_image=0x7f0b001f;
        public static final int com_facebook_picker_list_section_header=0x7f0b0023;
        public static final int com_facebook_picker_list_view=0x7f0b001a;
        public static final int com_facebook_picker_profile_pic_stub=0x7f0b0020;
        public static final int com_facebook_picker_row_activity_circle=0x7f0b001d;
        public static final int com_facebook_picker_search_text=0x7f0b002b;
        public static final int com_facebook_picker_title=0x7f0b0021;
        public static final int com_facebook_picker_title_bar=0x7f0b0028;
        public static final int com_facebook_picker_title_bar_stub=0x7f0b0027;
        public static final int com_facebook_picker_top_bar=0x7f0b0024;
        public static final int com_facebook_search_bar_view=0x7f0b002a;
        public static final int com_facebook_tooltip_bubble_view_bottom_pointer=0x7f0b0030;
        public static final int com_facebook_tooltip_bubble_view_text_body=0x7f0b002f;
        public static final int com_facebook_tooltip_bubble_view_top_pointer=0x7f0b002d;
        public static final int com_facebook_usersettingsfragment_login_button=0x7f0b0033;
        public static final int com_facebook_usersettingsfragment_logo_image=0x7f0b0031;
        public static final int com_facebook_usersettingsfragment_profile_name=0x7f0b0032;
        public static final int contents_supplement_text_view=0x7f0b0016;
        public static final int contents_text_view=0x7f0b0015;
        public static final int decode=0x7f0b0000;
        public static final int decode_failed=0x7f0b0001;
        public static final int decode_succeeded=0x7f0b0002;
        public static final int done_button=0x7f0b0037;
        public static final int format_text_view=0x7f0b0010;
        public static final int help_contents=0x7f0b0035;
        public static final int history_detail=0x7f0b0039;
        public static final int history_title=0x7f0b0038;
        public static final int image_view=0x7f0b0034;
        public static final int large=0x7f0b0007;
        public static final int launch_product_query=0x7f0b0003;
        public static final int menu_history_clear_text=0x7f0b0045;
        public static final int menu_history_send=0x7f0b0044;
        public static final int meta_text_view=0x7f0b0014;
        public static final int meta_text_view_label=0x7f0b0013;
        public static final int normal=0x7f0b0008;
        public static final int page_number_view=0x7f0b003d;
        public static final int picker_subtitle=0x7f0b0029;
        public static final int preview_view=0x7f0b000c;
        public static final int query_button=0x7f0b003b;
        public static final int query_text_view=0x7f0b003a;
        public static final int quit=0x7f0b0004;
        public static final int restart_preview=0x7f0b0005;
        public static final int result_button_view=0x7f0b0017;
        public static final int result_list_view=0x7f0b003c;
        public static final int result_view=0x7f0b000e;
        public static final int return_scan_result=0x7f0b0006;
        public static final int share_app_button=0x7f0b003f;
        public static final int share_bookmark_button=0x7f0b0040;
        public static final int share_clipboard_button=0x7f0b0042;
        public static final int share_contact_button=0x7f0b0041;
        public static final int share_text_view=0x7f0b0043;
        public static final int shopper_button=0x7f0b0018;
        public static final int small=0x7f0b0009;
        public static final int snippet_view=0x7f0b003e;
        public static final int status_view=0x7f0b0019;
        public static final int time_text_view=0x7f0b0012;
        public static final int type_text_view=0x7f0b0011;
        public static final int viewfinder_view=0x7f0b000d;
    }
    public static final class layout {
        public static final int bookmark_picker_list_item=0x7f030000;
        public static final int capture=0x7f030001;
        public static final int com_facebook_friendpickerfragment=0x7f030002;
        public static final int com_facebook_login_activity_layout=0x7f030003;
        public static final int com_facebook_picker_activity_circle_row=0x7f030004;
        public static final int com_facebook_picker_checkbox=0x7f030005;
        public static final int com_facebook_picker_image=0x7f030006;
        public static final int com_facebook_picker_list_row=0x7f030007;
        public static final int com_facebook_picker_list_section_header=0x7f030008;
        public static final int com_facebook_picker_search_box=0x7f030009;
        public static final int com_facebook_picker_title_bar=0x7f03000a;
        public static final int com_facebook_picker_title_bar_stub=0x7f03000b;
        public static final int com_facebook_placepickerfragment=0x7f03000c;
        public static final int com_facebook_placepickerfragment_list_row=0x7f03000d;
        public static final int com_facebook_search_bar_layout=0x7f03000e;
        public static final int com_facebook_tooltip_bubble=0x7f03000f;
        public static final int com_facebook_usersettingsfragment=0x7f030010;
        public static final int encode=0x7f030011;
        public static final int help=0x7f030012;
        public static final int history_list_item=0x7f030013;
        public static final int search_book_contents=0x7f030014;
        public static final int search_book_contents_header=0x7f030015;
        public static final int search_book_contents_list_item=0x7f030016;
        public static final int share=0x7f030017;
    }
    public static final class menu {
        public static final int capture=0x7f0c0000;
        public static final int encode=0x7f0c0001;
        public static final int history=0x7f0c0002;
    }
    public static final class raw {
        public static final int beep=0x7f050000;
    }
    public static final class string {
        public static final int app_name=0x7f08001c;
        /**  <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">QRコードスキャナー</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">Баркод Скенер</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">बारकोड स्कैनर</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">바코드 스캐너</string> 
 <string name="app_name">ماسح الرمز الشريطي</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barkod Tarayıcısı</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Barra-kode Eskanerra</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">Сканер штрих-кодов</string> 
 <string name="app_name">Barcode Scanner</string> 
 <string name="app_name">סורק ברקודים</string> 
 <string name="app_name">条码扫描器</string> 
 <string name="app_name">條碼掃描器</string> 
         */
        public static final int app_picker_name=0x7f08001d;
        public static final int bookmark_picker_name=0x7f08001e;
        public static final int button_add_calendar=0x7f08001f;
        public static final int button_add_contact=0x7f080020;
        public static final int button_back=0x7f080021;
        public static final int button_book_search=0x7f080022;
        public static final int button_cancel=0x7f080023;
        public static final int button_custom_product_search=0x7f080024;
        public static final int button_dial=0x7f080025;
        public static final int button_done=0x7f080026;
        public static final int button_email=0x7f080027;
        public static final int button_get_directions=0x7f080028;
        public static final int button_google_shopper=0x7f080029;
        public static final int button_mms=0x7f08002a;
        public static final int button_ok=0x7f08002b;
        public static final int button_open_browser=0x7f08002c;
        public static final int button_product_search=0x7f08002d;
        public static final int button_search_book_contents=0x7f08002e;
        public static final int button_share_app=0x7f08002f;
        public static final int button_share_bookmark=0x7f080030;
        public static final int button_share_by_email=0x7f080031;
        public static final int button_share_by_sms=0x7f080032;
        public static final int button_share_clipboard=0x7f080033;
        public static final int button_share_contact=0x7f080034;
        public static final int button_show_map=0x7f080035;
        public static final int button_sms=0x7f080036;
        public static final int button_web_search=0x7f080037;
        public static final int button_wifi=0x7f080038;
        public static final int com_facebook_choose_friends=0x7f08000f;
        public static final int com_facebook_dialogloginactivity_ok_button=0x7f080000;
        public static final int com_facebook_internet_permission_error_message=0x7f080013;
        public static final int com_facebook_internet_permission_error_title=0x7f080012;
        public static final int com_facebook_loading=0x7f080011;
        public static final int com_facebook_loginview_cancel_action=0x7f080006;
        public static final int com_facebook_loginview_log_in_button=0x7f080002;
        public static final int com_facebook_loginview_log_out_action=0x7f080005;
        public static final int com_facebook_loginview_log_out_button=0x7f080001;
        public static final int com_facebook_loginview_logged_in_as=0x7f080003;
        public static final int com_facebook_loginview_logged_in_using_facebook=0x7f080004;
        public static final int com_facebook_logo_content_description=0x7f080007;
        public static final int com_facebook_nearby=0x7f080010;
        public static final int com_facebook_picker_done_button_text=0x7f08000e;
        public static final int com_facebook_placepicker_subtitle_catetory_only_format=0x7f08000c;
        public static final int com_facebook_placepicker_subtitle_format=0x7f08000b;
        public static final int com_facebook_placepicker_subtitle_were_here_only_format=0x7f08000d;
        public static final int com_facebook_requesterror_password_changed=0x7f080016;
        public static final int com_facebook_requesterror_permissions=0x7f080018;
        public static final int com_facebook_requesterror_reconnect=0x7f080017;
        public static final int com_facebook_requesterror_relogin=0x7f080015;
        public static final int com_facebook_requesterror_web_login=0x7f080014;
        public static final int com_facebook_tooltip_default=0x7f080019;
        public static final int com_facebook_usersettingsfragment_log_in_button=0x7f080008;
        public static final int com_facebook_usersettingsfragment_logged_in=0x7f080009;
        public static final int com_facebook_usersettingsfragment_not_logged_in=0x7f08000a;
        public static final int contents_contact=0x7f080039;
        public static final int contents_email=0x7f08003a;
        public static final int contents_location=0x7f08003b;
        public static final int contents_phone=0x7f08003c;
        public static final int contents_sms=0x7f08003d;
        public static final int contents_text=0x7f08003e;
        public static final int fb_app_id=0x7f08001a;
        public static final int fb_app_name=0x7f08001b;
        public static final int history_clear_one_history_text=0x7f080040;
        public static final int history_clear_text=0x7f08003f;
        public static final int history_email_title=0x7f080041;
        public static final int history_empty=0x7f080042;
        public static final int history_empty_detail=0x7f080043;
        public static final int history_send=0x7f080044;
        public static final int history_title=0x7f080045;
        public static final int menu_encode_mecard=0x7f080046;
        public static final int menu_encode_vcard=0x7f080047;
        public static final int menu_help=0x7f080048;
        public static final int menu_history=0x7f080049;
        public static final int menu_settings=0x7f080094;
        public static final int menu_share=0x7f08004a;
        public static final int msg_bulk_mode_scanned=0x7f08004b;
        public static final int msg_camera_framework_bug=0x7f08004c;
        public static final int msg_default_format=0x7f08004d;
        public static final int msg_default_meta=0x7f08004e;
        public static final int msg_default_mms_subject=0x7f08004f;
        public static final int msg_default_status=0x7f080050;
        public static final int msg_default_time=0x7f080051;
        public static final int msg_default_type=0x7f080052;
        public static final int msg_encode_contents_failed=0x7f080053;
        public static final int msg_google_books=0x7f080054;
        public static final int msg_google_product=0x7f080055;
        public static final int msg_google_shopper_missing=0x7f080056;
        public static final int msg_install_google_shopper=0x7f080057;
        public static final int msg_intent_failed=0x7f080058;
        public static final int msg_redirect=0x7f080059;
        public static final int msg_sbc_book_not_searchable=0x7f08005a;
        public static final int msg_sbc_failed=0x7f08005b;
        public static final int msg_sbc_no_page_returned=0x7f08005c;
        public static final int msg_sbc_page=0x7f08005d;
        public static final int msg_sbc_results=0x7f08005e;
        public static final int msg_sbc_searching_book=0x7f08005f;
        public static final int msg_sbc_snippet_unavailable=0x7f080060;
        public static final int msg_sbc_unknown_page=0x7f080061;
        public static final int msg_share_explanation=0x7f080062;
        public static final int msg_share_subject_line=0x7f080063;
        public static final int msg_share_text=0x7f080064;
        public static final int msg_sure=0x7f080065;
        public static final int msg_unmount_usb=0x7f080066;
        public static final int preferences_actions_title=0x7f080067;
        public static final int preferences_auto_focus_title=0x7f080068;
        public static final int preferences_bulk_mode_summary=0x7f080069;
        public static final int preferences_bulk_mode_title=0x7f08006a;
        public static final int preferences_copy_to_clipboard_title=0x7f08006b;
        public static final int preferences_custom_product_search_summary=0x7f08006c;
        public static final int preferences_custom_product_search_title=0x7f08006d;
        public static final int preferences_decode_1D_title=0x7f08006e;
        public static final int preferences_decode_Data_Matrix_title=0x7f08006f;
        public static final int preferences_decode_QR_title=0x7f080070;
        public static final int preferences_device_bug_workarounds_title=0x7f080071;
        public static final int preferences_disable_continuous_focus_summary=0x7f080072;
        public static final int preferences_disable_continuous_focus_title=0x7f080073;
        public static final int preferences_disable_exposure_title=0x7f080074;
        public static final int preferences_front_light_summary=0x7f080075;
        public static final int preferences_front_light_title=0x7f080076;
        public static final int preferences_general_title=0x7f080077;
        public static final int preferences_name=0x7f080078;
        public static final int preferences_play_beep_title=0x7f080079;
        public static final int preferences_remember_duplicates_summary=0x7f08007a;
        public static final int preferences_remember_duplicates_title=0x7f08007b;
        public static final int preferences_result_title=0x7f08007c;
        public static final int preferences_scanning_title=0x7f08007d;
        public static final int preferences_search_country=0x7f08007e;
        public static final int preferences_supplemental_summary=0x7f080081;
        public static final int preferences_supplemental_title=0x7f080082;
        public static final int preferences_try_bsplus=0x7f08007f;
        public static final int preferences_try_bsplus_summary=0x7f080080;
        public static final int preferences_vibrate_title=0x7f080083;
        public static final int result_address_book=0x7f080084;
        public static final int result_calendar=0x7f080085;
        public static final int result_email_address=0x7f080086;
        public static final int result_geo=0x7f080087;
        public static final int result_isbn=0x7f080088;
        public static final int result_product=0x7f080089;
        public static final int result_sms=0x7f08008a;
        public static final int result_tel=0x7f08008b;
        public static final int result_text=0x7f08008c;
        public static final int result_uri=0x7f08008d;
        public static final int result_wifi=0x7f08008e;
        public static final int sbc_name=0x7f08008f;
        public static final int share_name=0x7f080090;
        public static final int wifi_changing_network=0x7f080091;
        public static final int wifi_ssid_label=0x7f080092;
        public static final int wifi_type_label=0x7f080093;
    }
    public static final class style {
        public static final int com_facebook_loginview_default_style=0x7f090000;
        public static final int com_facebook_loginview_silver_style=0x7f090001;
        public static final int tooltip_bubble_text=0x7f090002;
    }
    public static final class xml {
        public static final int config=0x7f040000;
        public static final int preferences=0x7f040001;
    }
    public static final class styleable {
        /** Attributes that can be used with a com_facebook_friend_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_friend_picker_fragment_multi_select net.karazy.cloobster.frizz:multi_select}</code></td><td></td></tr>
           </table>
           @see #com_facebook_friend_picker_fragment_multi_select
         */
        public static final int[] com_facebook_friend_picker_fragment = {
            0x7f010007
        };
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#multi_select}
          attribute's value can be found in the {@link #com_facebook_friend_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:multi_select
        */
        public static final int com_facebook_friend_picker_fragment_multi_select = 0;
        /** Attributes that can be used with a com_facebook_login_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_login_view_confirm_logout net.karazy.cloobster.frizz:confirm_logout}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_fetch_user_info net.karazy.cloobster.frizz:fetch_user_info}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_login_text net.karazy.cloobster.frizz:login_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_login_view_logout_text net.karazy.cloobster.frizz:logout_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_login_view_confirm_logout
           @see #com_facebook_login_view_fetch_user_info
           @see #com_facebook_login_view_login_text
           @see #com_facebook_login_view_logout_text
         */
        public static final int[] com_facebook_login_view = {
            0x7f01000c, 0x7f01000d, 0x7f01000e, 0x7f01000f
        };
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#confirm_logout}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:confirm_logout
        */
        public static final int com_facebook_login_view_confirm_logout = 0;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#fetch_user_info}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:fetch_user_info
        */
        public static final int com_facebook_login_view_fetch_user_info = 1;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#login_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:login_text
        */
        public static final int com_facebook_login_view_login_text = 2;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#logout_text}
          attribute's value can be found in the {@link #com_facebook_login_view} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:logout_text
        */
        public static final int com_facebook_login_view_logout_text = 3;
        /** Attributes that can be used with a com_facebook_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_background net.karazy.cloobster.frizz:done_button_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_done_button_text net.karazy.cloobster.frizz:done_button_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_extra_fields net.karazy.cloobster.frizz:extra_fields}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_pictures net.karazy.cloobster.frizz:show_pictures}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_show_title_bar net.karazy.cloobster.frizz:show_title_bar}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_bar_background net.karazy.cloobster.frizz:title_bar_background}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_picker_fragment_title_text net.karazy.cloobster.frizz:title_text}</code></td><td></td></tr>
           </table>
           @see #com_facebook_picker_fragment_done_button_background
           @see #com_facebook_picker_fragment_done_button_text
           @see #com_facebook_picker_fragment_extra_fields
           @see #com_facebook_picker_fragment_show_pictures
           @see #com_facebook_picker_fragment_show_title_bar
           @see #com_facebook_picker_fragment_title_bar_background
           @see #com_facebook_picker_fragment_title_text
         */
        public static final int[] com_facebook_picker_fragment = {
            0x7f010000, 0x7f010001, 0x7f010002, 0x7f010003,
            0x7f010004, 0x7f010005, 0x7f010006
        };
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#done_button_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name net.karazy.cloobster.frizz:done_button_background
        */
        public static final int com_facebook_picker_fragment_done_button_background = 6;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#done_button_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:done_button_text
        */
        public static final int com_facebook_picker_fragment_done_button_text = 4;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#extra_fields}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:extra_fields
        */
        public static final int com_facebook_picker_fragment_extra_fields = 1;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#show_pictures}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:show_pictures
        */
        public static final int com_facebook_picker_fragment_show_pictures = 0;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#show_title_bar}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:show_title_bar
        */
        public static final int com_facebook_picker_fragment_show_title_bar = 2;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#title_bar_background}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a reference to another resource, in the form "<code>@[+][<i>package</i>:]<i>type</i>:<i>name</i></code>"
or to a theme attribute in the form "<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>".
          @attr name net.karazy.cloobster.frizz:title_bar_background
        */
        public static final int com_facebook_picker_fragment_title_bar_background = 5;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#title_text}
          attribute's value can be found in the {@link #com_facebook_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:title_text
        */
        public static final int com_facebook_picker_fragment_title_text = 3;
        /** Attributes that can be used with a com_facebook_place_picker_fragment.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_radius_in_meters net.karazy.cloobster.frizz:radius_in_meters}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_results_limit net.karazy.cloobster.frizz:results_limit}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_search_text net.karazy.cloobster.frizz:search_text}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_place_picker_fragment_show_search_box net.karazy.cloobster.frizz:show_search_box}</code></td><td></td></tr>
           </table>
           @see #com_facebook_place_picker_fragment_radius_in_meters
           @see #com_facebook_place_picker_fragment_results_limit
           @see #com_facebook_place_picker_fragment_search_text
           @see #com_facebook_place_picker_fragment_show_search_box
         */
        public static final int[] com_facebook_place_picker_fragment = {
            0x7f010008, 0x7f010009, 0x7f01000a, 0x7f01000b
        };
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#radius_in_meters}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:radius_in_meters
        */
        public static final int com_facebook_place_picker_fragment_radius_in_meters = 0;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#results_limit}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be an integer value, such as "<code>100</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:results_limit
        */
        public static final int com_facebook_place_picker_fragment_results_limit = 1;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#search_text}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a string value, using '\\;' to escape characters such as '\\n' or '\\uxxxx' for a unicode character.
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:search_text
        */
        public static final int com_facebook_place_picker_fragment_search_text = 2;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#show_search_box}
          attribute's value can be found in the {@link #com_facebook_place_picker_fragment} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:show_search_box
        */
        public static final int com_facebook_place_picker_fragment_show_search_box = 3;
        /** Attributes that can be used with a com_facebook_profile_picture_view.
           <p>Includes the following attributes:</p>
           <table>
           <colgroup align="left" />
           <colgroup align="left" />
           <tr><th>Attribute</th><th>Description</th></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_is_cropped net.karazy.cloobster.frizz:is_cropped}</code></td><td></td></tr>
           <tr><td><code>{@link #com_facebook_profile_picture_view_preset_size net.karazy.cloobster.frizz:preset_size}</code></td><td></td></tr>
           </table>
           @see #com_facebook_profile_picture_view_is_cropped
           @see #com_facebook_profile_picture_view_preset_size
         */
        public static final int[] com_facebook_profile_picture_view = {
            0x7f010010, 0x7f010011
        };
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#is_cropped}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be a boolean value, either "<code>true</code>" or "<code>false</code>".
<p>This may also be a reference to a resource (in the form
"<code>@[<i>package</i>:]<i>type</i>:<i>name</i></code>") or
theme attribute (in the form
"<code>?[<i>package</i>:][<i>type</i>:]<i>name</i></code>")
containing a value of this type.
          @attr name net.karazy.cloobster.frizz:is_cropped
        */
        public static final int com_facebook_profile_picture_view_is_cropped = 1;
        /**
          <p>This symbol is the offset where the {@link net.karazy.cloobster.frizz.R.attr#preset_size}
          attribute's value can be found in the {@link #com_facebook_profile_picture_view} array.


          <p>Must be one of the following constant values.</p>
<table>
<colgroup align="left" />
<colgroup align="left" />
<colgroup align="left" />
<tr><th>Constant</th><th>Value</th><th>Description</th></tr>
<tr><td><code>small</code></td><td>-2</td><td> Keep in sync with constants in ProfilePictureView </td></tr>
<tr><td><code>normal</code></td><td>-3</td><td></td></tr>
<tr><td><code>large</code></td><td>-4</td><td></td></tr>
</table>
          @attr name net.karazy.cloobster.frizz:preset_size
        */
        public static final int com_facebook_profile_picture_view_preset_size = 0;
    };
}
